"""update category

Revision ID: 01be83912d41
Revises: 9fea0628490c
Create Date: 2024-12-03 21:27:41.354070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01be83912d41'
down_revision = '9fea0628490c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
