"""empty message

Revision ID: 339a2b1f6fab
Revises: 6edf6c6125ee
Create Date: 2025-01-21 21:36:02.327898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '339a2b1f6fab'
down_revision = '6edf6c6125ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_course', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=250),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=250),
               existing_nullable=False)
        batch_op.drop_column('expired_time')

    with op.batch_alter_table('content_course', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
