"""adding subscribe type

Revision ID: 664e3a63d960
Revises: 339a2b1f6fab
Create Date: 2025-01-21 21:43:56.917888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664e3a63d960'
down_revision = '339a2b1f6fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe_type',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe_type')
    # ### end Alembic commands ###
