"""alter table courses add img_banner

Revision ID: 6edf6c6125ee
Revises: cf016ec02f01
Create Date: 2024-12-05 22:24:56.388071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edf6c6125ee'
down_revision = 'cf016ec02f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_banner', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('img_banner')

    # ### end Alembic commands ###
