"""alter history_subscribe from price to subscribe_id

Revision ID: bcf37cd98a07
Revises: 664e3a63d960
Create Date: 2025-01-21 22:01:48.027190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcf37cd98a07'
down_revision = '664e3a63d960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_subscribe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribe_id', sa.String(length=36), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_subscribe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('subscribe_id')

    # ### end Alembic commands ###
