"""update history subscribe

Revision ID: d4e8e13ad7de
Revises: bcf37cd98a07
Create Date: 2025-01-21 22:30:11.872739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e8e13ad7de'
down_revision = 'bcf37cd98a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_subscribe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('status_payment', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('account_no', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_subscribe', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('account_no')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('status_payment')
        batch_op.drop_column('transaction_date')

    # ### end Alembic commands ###
